#!/bin/bash

# ASCII Art
ascii_art="
       _ _     _                 
      | (_)   | |                
      | |_ ___| |__  _ __  _   _ 
  _   | | / __| '_ \| '_ \| | | |
 | |__| | \__ \ | | | | | | |_| |
  \____/|_|___/_| |_|_| |_|\__,_|
                                 
"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Function to display messages
echo_message() {
  echo -e "${GREEN}$1${NC}"
}

# Clear the screen
clear

# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root.${NC}"
  exit 1
fi

echo -e "${CYAN}$ascii_art${NC}"

echo_message "* Installing Dependencies"

# Update package list and install dependencies
apt update
apt install -y curl software-properties-common git

# Install Node.js 20
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt install -y nodejs

echo_message "* Installed Dependencies"

echo_message "* Installing Files"

# Create directory, clone repository, and install dependencies
mkdir -p hosting
cd hosting || { echo_message "Failed to change directory to hosting"; exit 1; }
git clone https://github.com/jhondrheydacudao/Hosting.git

cd Hosting || { echo_message "Failed to change directory to Hosting"; exit 1; }
npm install

echo_message "* Installed Files"

echo_message "* Running Setup Scripts"

# Run setup scripts
npm run seed
npm run createUser

echo_message "* Starting Hosting with PM2"

# Install PM2 and start the application
npm install -g pm2
pm2 start index.js

echo_message "* Hosting Installed and Started on Port 3001"

# Clear the screen after finishing
clear
echo "Made by Jhondrhey"
