#!/bin/bash

# ASCII Art
ascii_art="

       _ _     _                 
      | (_)   | |                
      | |_ ___| |__  _ __  _   _ 
  _   | | / __| '_ \| '_ \| | | |
 | |__| | \__ \ | | | | | | |_| |
  \____/|_|___/_| |_|_| |_|\__,_|
                                 
"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Clear the screen
clear

# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root.${NC}"
  exit 1
fi

echo -e "${CYAN}$ascii_art${NC}"

echo "* Installing Dependencies"

# Update package list and install dependencies
sudo apt update
sudo apt install -y curl software-properties-common git
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs 

echo "* Dependencies Installed"

echo "* Cloning Repository"

# Clone repository
git clone https://github.com/jhondrheydacudao/Hosting.git
cd Hosting || { echo "Failed to change directory to Hosting"; exit 1; }

echo "* Installing NPM Packages"
npm install

echo "* Starting Server with PM2"

# Install PM2 and start the application
sudo npm install -g pm2
pm2 start index.js --name Hosting
pm2 save

echo "* Installation Complete!"
echo "* Hosting Panel is running on Port 3001"
