#!/bin/bash

# ASCII Art
ascii_art="
       _ _     _                 
      | (_)   | |                
      | |_ ___| |__  _ __  _   _ 
  _   | | / __| '_ \| '_ \| | | |
 | |__| | \__ \ | | | | | | |_| |
  \____/|_|___/_| |_|_| |_|\__,_|
                                 
"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Function for logging messages
echo_message() {
  echo -e "${GREEN}$1${NC}"
}

# Clear the screen
clear

# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root.${NC}"
  exit 1
fi

echo -e "${CYAN}$ascii_art${NC}"

echo_message "* Installing Dependencies"

# Update package list and install dependencies
sudo apt update && sudo apt upgrade -y
sudo apt install -y curl software-properties-common git

# Install Node.js
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - || { echo -e "${RED}Failed to setup Node.js repository.${NC}"; exit 1; }
sudo apt install -y nodejs || { echo -e "${RED}Failed to install Node.js.${NC}"; exit 1; }

echo_message "* Dependencies Installed"

echo_message "* Cloning Repository"

# Create directory, clone repository, and navigate
mkdir -p ~/hosting
cd ~/hosting || { echo_message "Failed to change directory to hosting"; exit 1; }
git clone https://github.com/jhondrheydacudao/Hosting.git || { echo -e "${RED}Failed to clone repository.${NC}"; exit 1; }
cd Hosting || { echo -e "${RED}Failed to enter Hosting directory.${NC}"; exit 1; }

echo_message "* Repository Cloned"

echo_message "* Installing Project Dependencies"

# Install project dependencies
npm install || { echo -e "${RED}Failed to install Node.js dependencies.${NC}"; exit 1; }

echo_message "* Project Dependencies Installed"

echo_message "* Setting up PM2"

# Install PM2 globally and start the application
sudo npm install -g pm2 || { echo -e "${RED}Failed to install PM2.${NC}"; exit 1; }
pm2 start index.js --name "Oversee"

echo_message "* Oversee Installed and Running on Port 3001"

# Save PM2 process and enable startup
pm2 save
pm2 startup systemd

echo_message "* PM2 Process Saved and Enabled at Startup"

# Final message
clear
echo -e "${GREEN}Installation complete! Oversee is running.${NC}"
echo "Made by Jishnu"
